package com.expense_tracker.Expense.Tracker.rest;

import com.expense_tracker.Expense.Tracker.model.*;
import com.expense_tracker.Expense.Tracker.securityconfig.ExpenseTrackerUserDetailsService;
import com.expense_tracker.Expense.Tracker.service.User;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import jakarta.annotation.PostConstruct;
import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.crypto.factory.PasswordEncoderFactories;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.*;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.util.Date;

@RestController
@Component
public class UserController {

    private final String key=ApplicationConstants.key;


    User user;
    private ModelMapper modelMapper;
    PasswordEncoder passwordEncoder;
    AuthenticationManager authenticationManager;
    @Autowired
    public UserController(User user, ModelMapper modelMapper, PasswordEncoder passwordEncoder,
                          AuthenticationManager authenticationManager) {
        this.user = user;
        this.modelMapper=modelMapper;
        this.passwordEncoder=passwordEncoder;
        this.authenticationManager=authenticationManager;
    }

    @PostMapping("/user/register")
    public ResponseEntity<UserResponseDTO> saveUser(@RequestBody UserRequestDTO userRequestDTO) {
        UserDetails userDetails = modelMapper.map(userRequestDTO, UserDetails.class);
        userDetails.setPassword(passwordEncoder.encode(userRequestDTO.password()));
        int userID = user.saveUser(userDetails);
        return ResponseEntity.ok(new UserResponseDTO(userID));
    }

    @PutMapping("/user/register")
    public ResponseEntity<UserResponseDTO> modifyUser(@RequestBody UserRequestDTO userRequestDTO) {
        UserDetails userDetails = modelMapper.map(userRequestDTO, UserDetails.class);
        int userID = user.modifyUserDetails(userDetails);
        return ResponseEntity.ok(new UserResponseDTO(userID));
    }

    @DeleteMapping("/user/{userId}")
    public ResponseEntity<UserResponseDTO> deleteUser(@PathVariable int userId) {
        int userID = user.deleteUser(userId);
        return ResponseEntity.ok(new UserResponseDTO(userID));
    }

    @GetMapping("/user/{userId}")
    public ResponseEntity<UserDetailsResponseDTO> getUser(@PathVariable int userId) {
        UserDetails userDetails =  user.getUser(userId);
        UserDetailsResponseDTO dto = new UserDetailsResponseDTO(
                userDetails.getUserId(),
                userDetails.getUserName(),
                userDetails.getFirstName(),
                userDetails.getLastName()
        );
        return ResponseEntity.ok(dto);
    }

    @PostMapping("/user/login")
    public ResponseEntity<JWTTokenDTO> loginUser(@RequestBody JWTTokenRequestDTO jwtTokenRequestDTO) {
        //token can be generated by giving the email and password in the request using the provider manager bean
        String userName =jwtTokenRequestDTO.userName();
        String password =jwtTokenRequestDTO.password();
        Authentication authentication = UsernamePasswordAuthenticationToken.unauthenticated(userName, password);
        Authentication authenticated = authenticationManager.authenticate(authentication);
        String token="";
        if(authenticated.isAuthenticated()) {
            SecretKey secretKey= Keys.hmacShaKeyFor(key.getBytes(StandardCharsets.UTF_8));
            token = Jwts.builder()
                    .issuer("Expense tracker")
                    .subject("JWT Token for security")
                    .claim("username",userName)
                    .issuedAt(new Date())
                    .expiration(new Date(new Date().getTime()+6000000))
                    .signWith(secretKey).compact();
        }
        return ResponseEntity.status(HttpStatus.OK).header("token",token).body(new JWTTokenDTO(token));
    }

    @GetMapping("/users/{userId}/savings/compare")
    public ResponseEntity<CompareMonthlySavingsDTO> compareMonthlySavings(
            @PathVariable int userId,
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate firstMonthStart, // Format: YYYY-MM
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate firstMonthEnd,
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate secondMonthStart, // Format: YYYY-MM
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate secondMonthEnd
    ) {
        CompareMonthlySavingsDTO compareMonthlySavingsDTO = user.comparingMonthlySavingsDTO(userId,firstMonthStart,firstMonthEnd,secondMonthStart,secondMonthEnd);
        return ResponseEntity.ok(compareMonthlySavingsDTO);
    }





}
